In [21]:
import os
import numpy as np
import pandas as pd
f_app = os.path.join('./data/', 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 練習時間
##### 資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？
##### 資料的 row 數以及 column 數

In [22]:
print('len : Column Count = %i, Row Count = %i' % (len(app_train.columns), (len(app_train.index))))
print('shape : Column Count = %i, Row Count = %i' % (app_train.shape[1], app_train.shape[0]))

len : Column Count = 122, Row Count = 307511
shape : Column Count = 122, Row Count = 307511

##### 列出所有欄位

In [25]:
print('%s' %(app_train.columns.tolist()))# 只有欄位名稱, 沒有型態

['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR']

##### 截取部分資料

In [37]:
print(app_train[100:102]) # [r1:r2] 從第r1列開始取到第r2-1列

     SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
100      100119       0    Revolving loans           F            N
101      100120       0         Cash loans           F            N

    FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
100               Y             0           54000.0    180000.0       9000.0
101               N             0          135000.0    781920.0      28215.0

     ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
100  ...                 0                0                0                0
101  ...                 0                0                0                0

    AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
100                        0.0                       0.0
101                        0.0                       0.0

     AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
100                         0.0                        0.0
101                         0.0                        0.0

     AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR
100                        0.0                         0.0
101                        0.0                         0.0

[2 rows x 122 columns]

In [48]:
filter_1 = (app_train['CODE_GENDER']=='F')# 取得 CODE_GENDER 等於 F 的過濾器
filter_2 = (app_train['FLAG_OWN_CAR']=='Y')# 取得 FLAG_OWN_CAR 等於 Y 的過濾器
print(app_train[filter_1 & filter_2])# 只列出滿足過濾器的資料列

        SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
6           100009       0         Cash loans           F            Y
21          100025       0         Cash loans           F            Y
66          100078       0         Cash loans           F            Y
86          100101       0         Cash loans           F            Y
93          100111       0         Cash loans           F            Y
109         100129       0    Revolving loans           F            Y
117         100137       0         Cash loans           F            Y
124         100145       0         Cash loans           F            Y
134         100156       0         Cash loans           F            Y
142         100164       0         Cash loans           F            Y
143         100165       0         Cash loans           F            Y
152         100179       0         Cash loans           F            Y
164         100193       0         Cash loans           F            Y
167         100196       0         Cash loans           F            Y
185         100215       0         Cash loans           F            Y
192         100224       0         Cash loans           F            Y
215         100250       0         Cash loans           F            Y
237         100275       0         Cash loans           F            Y
238         100276       0         Cash loans           F            Y
242         100282       1    Revolving loans           F            Y
272         100315       0         Cash loans           F            Y
281         100324       0         Cash loans           F            Y
286         100329       0         Cash loans           F            Y
291         100336       1         Cash loans           F            Y
316         100363       0         Cash loans           F            Y
323         100371       0         Cash loans           F            Y
326         100374       0         Cash loans           F            Y
330         100378       0         Cash loans           F            Y
356         100410       0         Cash loans           F            Y
358         100412       0         Cash loans           F            Y
...            ...     ...                ...         ...          ...
307317      456041       0         Cash loans           F            Y
307322      456046       0         Cash loans           F            Y
307339      456064       0         Cash loans           F            Y
307340      456065       0         Cash loans           F            Y
307345      456070       0         Cash loans           F            Y
307358      456083       0         Cash loans           F            Y
307359      456084       0         Cash loans           F            Y
307360      456085       0         Cash loans           F            Y
307361      456086       0         Cash loans           F            Y
307363      456088       1         Cash loans           F            Y
307371      456096       0         Cash loans           F            Y
307393      456126       0         Cash loans           F            Y
307397      456130       0         Cash loans           F            Y
307401      456134       0         Cash loans           F            Y
307407      456140       1         Cash loans           F            Y
307408      456141       0         Cash loans           F            Y
307414      456147       0         Cash loans           F            Y
307416      456149       0         Cash loans           F            Y
307427      456160       0         Cash loans           F            Y
307434      456172       0         Cash loans           F            Y
307437      456175       0         Cash loans           F            Y
307445      456183       0         Cash loans           F            Y
307452      456191       0         Cash loans           F            Y
307456      456195       0         Cash loans           F            Y
307462      456201       0         Cash loans           F            Y
307473      456213       0         Cash loans           F            Y
307482      456226       0         Cash loans           F            Y
307484      456228       0         Cash loans           F            Y
307486      456230       0         Cash loans           F            Y
307497      456241       0         Cash loans           F            Y

       FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
6                    Y             1          171000.0   1560726.0
21                   Y             1          202500.0   1132573.5
66                   Y             0          180000.0   1035000.0
86                   Y             0          202500.0    343377.0
93                   N             1          112500.0    862560.0
109                  Y             1           85500.0    135000.0
117                  Y             0          225000.0    891072.0
124                  Y             1          202500.0    260725.5
134                  N             2          157500.0    945000.0
142                  N             1          450000.0    407434.5
143                  Y             0          175500.0   1293502.5
152                  N             0          202500.0    675000.0
164                  N             0          225000.0    296280.0
167                  Y             0          164250.0    755190.0
185                  N             0           90000.0    227520.0
192                  Y             2          225000.0   1256400.0
215                  N             1           72000.0     90000.0
237                  Y             0          108000.0    646920.0
238                  Y             0          135000.0    497520.0
242                  Y             0           73341.0    135000.0
272                  Y             1          121500.0    288873.0
281                  Y             1          112500.0    152820.0
286                  Y             0          135000.0    247275.0
291                  Y             0          157500.0    497520.0
316                  Y             1          360000.0    493497.0
323                  Y             1          450000.0    808650.0
326                  Y             2          112500.0   1308964.5
330                  Y             1          247500.0    808650.0
356                  N             0          180000.0   1258650.0
358                  Y             2          135000.0    318528.0
...                ...           ...               ...         ...
307317               Y             1          202500.0    599544.0
307322               Y             0          144000.0    450000.0
307339               Y             1          184500.0    540000.0
307340               Y             0          225000.0    481500.0
307345               N             0          180000.0    840996.0
307358               Y             2          112500.0    361462.5
307359               Y             1           99000.0    675000.0
307360               Y             0          135000.0    218016.0
307361               Y             0           92250.0    253737.0
307363               Y             0           29250.0    663093.0
307371               Y             0          112500.0    728460.0
307393               Y             0          202500.0    544500.0
307397               Y             0          202500.0    753840.0
307401               Y             0          135000.0   1718473.5
307407               Y             1          261000.0    711454.5
307408               Y             1          112500.0    237024.0
307414               Y             2           90000.0   1078200.0
307416               Y             0           90000.0    327024.0
307427               Y             0          270000.0   1298970.0
307434               Y             0           76500.0    163098.0
307437               Y             0           81000.0    180000.0
307445               Y             0          180000.0    990000.0
307452               N             2          153000.0   1350000.0
307456               Y             0           94500.0    270000.0
307462               Y             3          135000.0   1024785.0
307473               Y             1           90000.0    258709.5
307482               Y             0          225000.0    500566.5
307484               N             0          540000.0    545040.0
307486               Y             1          292500.0    355536.0
307497               Y             0          180000.0    270126.0

        AMT_ANNUITY  ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20  \
6           41301.0  ...                 0                0                0
21          37561.5  ...                 0                0                0
66          43983.0  ...                 0                0                0
86          22072.5  ...                 0                0                0
93          27954.0  ...                 0                0                0
109          6750.0  ...                 0                0                0
117         45625.5  ...                 0                0                0
124         16789.5  ...                 0                0                0
134         39127.5  ...                 0                0                0
142         43362.0  ...                 0                0                0
143         35568.0  ...                 0                0                0
152         53329.5  ...                 0                0                0
164         15124.5  ...                 0                0                0
167         32125.5  ...                 0                0                0
185          8172.0  ...                 0                0                0
192         36864.0  ...                 0                0                0
215          6529.5  ...                 0                0                0
237         18670.5  ...                 0                0                0
238         39438.0  ...                 0                0                0
242          6750.0  ...                 1                0                0
272         21064.5  ...                 0                0                0
281         18265.5  ...                 0                0                0
286         17716.5  ...                 0                0                0
291         28692.0  ...                 0                0                0
316         48942.0  ...                 0                0                0
323         31464.0  ...                 0                0                0
326         42354.0  ...                 0                0                0
330         26217.0  ...                 0                0                0
356         56277.0  ...                 0                0                0
358         25294.5  ...                 0                0                0
...             ...  ...               ...              ...              ...
307317      21663.0  ...                 0                0                0
307322      30573.0  ...                 0                0                0
307339      30150.0  ...                 0                0                0
307340      26118.0  ...                 0                0                0
307345      24718.5  ...                 0                0                0
307358      16051.5  ...                 0                0                0
307359      21906.0  ...                 0                0                0
307360      15993.0  ...                 0                0                0
307361      16956.0  ...                 0                0                0
307363      21519.0  ...                 0                0                0
307371      39676.5  ...                 0                0                0
307393      15921.0  ...                 0                0                0
307397      22171.5  ...                 0                0                0
307401      47385.0  ...                 0                0                0
307407      47673.0  ...                 0                0                0
307408      18855.0  ...                 0                0                0
307414      31653.0  ...                 0                0                0
307416      21982.5  ...                 0                0                0
307427      46786.5  ...                 0                0                0
307434      16015.5  ...                 0                0                0
307437      12658.5  ...                 0                0                0
307445      42075.0  ...                 0                0                0
307452      46926.0  ...                 0                0                0
307456      15075.0  ...                 0                0                0
307462      57222.0  ...                 0                0                0
307473      20439.0  ...                 0                0                0
307482      34969.5  ...                 0                0                0
307484      35617.5  ...                 0                0                0
307486      18283.5  ...                 0                0                0
307497      12028.5  ...                 0                0                0

       FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
6                     0                        0.0                       0.0
21                    0                        0.0                       0.0
66                    0                        0.0                       0.0
86                    0                        NaN                       NaN
93                    0                        0.0                       0.0
109                   0                        1.0                       0.0
117                   0                        NaN                       NaN
124                   0                        0.0                       0.0
134                   0                        0.0                       0.0
142                   0                        0.0                       0.0
143                   0                        0.0                       0.0
152                   0                        0.0                       0.0
164                   0                        0.0                       0.0
167                   0                        0.0                       0.0
185                   0                        0.0                       0.0
192                   0                        0.0                       0.0
215                   0                        0.0                       0.0
237                   0                        0.0                       0.0
238                   0                        0.0                       0.0
242                   0                        NaN                       NaN
272                   0                        0.0                       0.0
281                   0                        NaN                       NaN
286                   0                        0.0                       0.0
291                   0                        0.0                       0.0
316                   0                        1.0                       0.0
323                   0                        0.0                       0.0
326                   0                        0.0                       0.0
330                   0                        0.0                       0.0
356                   0                        NaN                       NaN
358                   0                        NaN                       NaN
...                 ...                        ...                       ...
307317                0                        0.0                       0.0
307322                0                        0.0                       0.0
307339                0                        0.0                       0.0
307340                0                        0.0                       0.0
307345                0                        0.0                       0.0
307358                0                        0.0                       0.0
307359                0                        0.0                       0.0
307360                0                        NaN                       NaN
307361                0                        NaN                       NaN
307363                0                        0.0                       0.0
307371                0                        0.0                       0.0
307393                0                        0.0                       0.0
307397                0                        0.0                       0.0
307401                0                        0.0                       0.0
307407                0                        0.0                       0.0
307408                0                        0.0                       0.0
307414                0                        0.0                       0.0
307416                0                        0.0                       0.0
307427                0                        0.0                       0.0
307434                0                        0.0                       0.0
307437                0                        0.0                       0.0
307445                0                        0.0                       0.0
307452                0                        0.0                       0.0
307456                0                        0.0                       0.0
307462                0                        0.0                       0.0
307473                0                        0.0                       0.0
307482                0                        0.0                       0.0
307484                0                        NaN                       NaN
307486                0                        0.0                       0.0
307497                0                        0.0                       0.0

        AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
6                              0.0                        1.0
21                             0.0                        0.0
66                             0.0                        0.0
86                             NaN                        NaN
93                             0.0                        0.0
109                            0.0                        0.0
117                            NaN                        NaN
124                            0.0                        0.0
134                            0.0                        1.0
142                            0.0                        0.0
143                            0.0                        0.0
152                            0.0                        1.0
164                            0.0                        1.0
167                            0.0                        0.0
185                            0.0                        5.0
192                            0.0                        0.0
215                            0.0                        0.0
237                            0.0                        0.0
238                            0.0                        0.0
242                            NaN                        NaN
272                            0.0                        0.0
281                            NaN                        NaN
286                            0.0                        0.0
291                            0.0                        0.0
316                            0.0                        0.0
323                            0.0                        0.0
326                            0.0                        0.0
330                            0.0                        0.0
356                            NaN                        NaN

In [49]:
print(len(app_train[filter_1].index)) # 滿足過濾器的 row 數
print(len(app_train[filter_2].index)) # 滿足過濾器的 row 數
print(len(app_train[filter_1 & filter_2].index)) # 滿足過濾器的 row 數

202448
104587
44959